services:
  db:
    image: supabase/postgres:15.1.0.93
    container_name: supabase-db
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - supabase-net

  kong:
    image: kong:3.3
    container_name: supabase-kong
    restart: always
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/var/lib/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - supabase-net

  gotrue:
    image: supabase/gotrue:v2.61.0
    restart: always
    environment:
      GOTRUE_JWT_SECRET: Rn9oUXYcLrbWsLSpi4BkdypgFkxVXi3emuoAphK3LSQ=
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:supersecret@db:5432/postgres
    depends_on:
      - db
    networks:
      - supabase-net

  postgrest:
    image: postgrest/postgrest:v11.2.0
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:supersecret@db:5432/postgres
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: Rn9oUXYcLrbWsLSpi4BkdypgFkxVXi3emuoAphK3LSQ=
    depends_on:
      - db
    networks:
      - supabase-net

  realtime:
    image: supabase/realtime:v2.29.2
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: supersecret
      JWT_SECRET: Rn9oUXYcLrbWsLSpi4BkdypgFkxVXi3emuoAphK3LSQ=
    depends_on:
      - db
    networks:
      - supabase-net

  storage:
    image: supabase/storage-api:v1.11.13
    restart: always
    environment:
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      PGRST_JWT_SECRET: Rn9oUXYcLrbWsLSpi4BkdypgFkxVXi3emuoAphK3LSQ=
      POSTGREST_URL: http://postgrest:3000
      STORAGE_BACKEND: s3
      FILE_STORAGE_BACKEND: s3
      #FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      FILE_SIZE_LIMIT: 52428800
      REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      GLOBAL_S3_BUCKET: uploads
      GLOBAL_S3_ENDPOINT: https://s3.mondaha.com
      GLOBAL_S3_PROTOCOL: https
      GLOBAL_S3_FORCE_PATH_STYLE: true
      # AWS_ACCESS_KEY_ID: minio
      # AWS_SECRET_ACCESS_KEY: minio123
      AWS_ACCESS_KEY_ID: iNfTcxdJRw2IqIhnDAD8
      AWS_SECRET_ACCESS_KEY: Ggp9ugLPlh5YlFamLgFwapAKBMOHWKVhnHfLluey
      ENABLE_IMAGE_TRANSFORMATION: "true"
    depends_on:
      - postgrest
      - minio
    networks:
      - supabase-net

  minio:
    image: minio/minio
    container_name: supabase-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - supabase-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5

  studio:
    image: supabase/studio:v0.23.08
    restart: always
    ports:
      - "8080:3000"
    environment:
      SUPABASE_PUBLIC_URL: http://localhost:8080
      SUPABASE_URL: http://localhost:8080
      POSTGRES_PASSWORD: supersecret
    depends_on:
      - db
    networks:
      - supabase-net

volumes:
  pg_data:
  minio_data:

networks:
  supabase-net:
